### ISSUE TITLE
libxml2 not found when building libxslt

### ISSUE THREAD

**Issue by jbheuschen** [gnustep/tools-android#10]
```
[...]
checking for fprintf... yes
checking for snprintf... yes
checking for vfprintf... yes
checking for vsprintf... yes
checking for vsnprintf... yes
checking for sscanf... yes
checking for clock_gettime... yes
checking for perl... perl
checking for python... /usr/bin/python
PYTHON is pointing at /usr/bin/python
Found Python version 2.7
Found libxml2-python module
could not find python2.7/Python.h
Disabling crypto support
Enabling debugger
Enabling profiler
checking for armv7a-linux-androideabi-xml2-config... no
checking for xml2-config... /Users/jbheuschen/Library/Android/GNUstep/armeabi-v7a/bin/xml2-config
configure: error: Could not find libxml2 anywhere, check ftp://xmlsoft.org/.

### phases/17-libxslt.sh failed for ABI armeabi-v7a

The previous toolchain build has been restored. The failed build can be found at:
/Users/jbheuschen/Library/Android/GNUstep.failed
```

Unfortunately, I'm unable to build the project as the libxslt-phase always fails to configure, saying it couldn't find the previously-built libxml2. The libxml2 build-phase, however, compiles and installs successfully. Hence, the libxml2 files in "Android/GNUStep/amreabi-v7a" are present, too. I have to admit, though, that I'm not very experienced with this kind of stuff - I hope I didn't miss something. Is this a known problem and can it be fixed? Thanks in advance for any help!

My system:
OS: _macOS 11.3.1 (M1/arm64)_
CMake: _3.20.2_
Android NDK: _22.1.7171670_
[build.log](https://github.com/gnustep/tools-android/files/6489095/build.log)

**Comment by triplef** [comment]
I can also reproduce this here. Looks like libxml2 released an [update](https://github.com/GNOME/libxml2/releases/tag/v2.9.12) a couple days ago, and since our scripts always use the latest release I’m guessing that this update broke something. I’ll take a look.

**Comment by triplef** [comment]
This should be fixed. Let me know if you run into any further issues!
