### ISSUE TITLE
Build fails as local `libidn2` installation is incorrectly picked up by libcurl

### ISSUE THREAD

**Issue by hmelder** [gnustep/tools-android#23]
See https://github.com/curl/curl/issues/14405 and fix https://github.com/curl/curl/commit/515440a2f29e720e09b4942f8a9106418f728410

**Comment by triplef** [comment]
Is this an issue with Windows or Android?

**Comment by hmelder** [comment]
This occurs when building tools-android on a device that has libidn2 installed.
