### ISSUE TITLE
macos  ld.lld: error:  libicudata.so: unknown file type

### ISSUE THREAD

**Issue by guanzidashu** [gnustep/tools-android#26]
ld.lld: error: /Volumes/Lenovo/Android/GNUstep/armeabi-v7a/lib/libicudata.so: unknown file type
ld.lld: error: /Volumes/Lenovo/Android/GNUstep/armeabi-v7a/lib/libicudata.so: unknown file type
clang-17: error: linker command failed with exit code 1 (use -v to see invocation)
clang-17: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [xmlcatalog] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [xmllint] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

### phases/16-libxml2.sh failed for ABI armeabi-v7a
this version ![image](https://github.com/user-attachments/assets/526e9691-6f19-4ac6-9e54-6044fb74f001)
command : ./build.sh  --prefix /Volumes/Lenovo/Android/GNUstep -n /Users/hachi/Library/Android/sdk/ndk/26.1.10909125 
branch :master

**Comment by triplef** [comment]
Can you check the type of libicudata.so by running this?

```
$ file /Volumes/Lenovo/Android/GNUstep/armeabi-v7a/lib/libicudata.so
```

For me the output is this:
```
ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), static-pie linked, BuildID[sha1]=2c57548568adc3435b2e76204b97d65c7df8846f, not stripped
```

**Comment by guanzidashu** [comment]
no, it only displays data, not elf32.
![image](https://github.com/user-attachments/assets/494fb91a-a1a2-4147-b21a-18f43ac01f2f)
[build.log](https://github.com/user-attachments/files/17037731/build.log)

**Comment by triplef** [comment]
Maybe the symlink is broken? Can you try deleting the ~/Library/Android/GNUstep folder and building again?
