### ISSUE TITLE
iOS Runloop to android looper

### ISSUE THREAD

**Issue by guanzidashu** [gnustep/tools-android#27]
GNUstep base currently has no native integration between the Android run-loop and NSRunLoop or the libdispatch main queue, so things like -performSelector:withObject:afterDelay: or dispatching on dispatch_get_main_queue() will not work out of the box. An integration depends on the setup of the app (e.g. whether using Android Studio, Qt, or something else), and is possible to add in the app by swizzing NSRunLoop. Feel free to open an issue if this is of interest to you and you would like more information.

Could you please recommend a demo for reference?

**Comment by triplef** [comment]
Here’s our integration with the Qt runloop: [GSRunLoopManager.zip](https://github.com/user-attachments/files/17039783/GSRunLoopManager.zip)

On launch you just need to instantiate a `GSRunLoopManager` object, which will then swizzle `NSRunLoop` to integrate it with the Qt runloop.

I don’t have an implementation without using Qt, but maybe this will help you to write one.

**Comment by guanzidashu** [comment]
Thank you very much, I will try to integrate it into Android.

**Comment by triplef** [comment]
Great, feel free to share any solution here for others. 🙏
