### ISSUE TITLE
How can I learn more about it?

### ISSUE THREAD

**Issue by mePy2** [gnustep/tools-android#3]
Hi,

I would like to know more about the project.
Put simply, what’s this about and what I can do with this? Writing Android apps using Objective-C?
What would be the pros?

Best

**Comment by triplef** [comment]
This project allows you to use Objective C code in an Android app. While it won’t allow you to write an entire Android app in Objective C, it lets you implement parts of an app in Objective C using the Foundation framework (just like when using the NDK to integrate C/C++ as native code) and integrate that code with other Java code. You could also say that it extends the NDK to support Objective C in addition to C and C++.

In our case it is used to create an Android app from a large existing Objective C code base by taking the existing model / business logic code (which depends only on the Foundation framework), and combining it with a new UI layer and system integration points (e.g. interfacing with Java APIs to access system services).

Let me know if that answers your question.

**Comment by mePy2** [comment]
Hi @triplef 

Thank you. Yes, you answered my question.
If I’ll have something more to ask, I will write it here. I would give it a try but I have just started programming on Android, actually I have no experience with it.
Do you have some beginners tutorial about Android development using the NDK?

Best

**Comment by triplef** [comment]
Great. I’d take a look at the [guides](https://developer.android.com/ndk/guides) and [samples](https://developer.android.com/ndk/samples) available on the NDK website to get started.
